Update <if> and <variable>

diff --git a/<if> and <variable> b/<if> and <variable>
--- a/<if> and <variable>
+++ b/<if> and <variable>
@@ -1,4 +1,12 @@
 #!/bin/bash - пишу какой интерпретатор использовать
+RESULT = $(ls /etc) - так обьявляется переменная (знак $ обязателен!)
+if [[ $RESULT == *"apt"* && $? == 0]]; условие if. * - произвольное количиство символов; $? - код ошибки (0 значит что ошибки нет)
+then echo "good" - вывод на экран SUCCESS
+else echo "FAIL" вывод на экран FAIL
+fi
+
+
+#!/bin/bash 
 RESULT=$(ls /etc) - так обьявляется переменная (знак $ обязателен!)
 if [[ $RESULT = *"apt"* & $? = 0 ]]; - условие if
 then echo "SUCCESS" - вывод на экран SUCCESS
